spring.datasource:
  url: jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#shareable h2 database: jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
  username: sa
  password: sa
spring.h2.console.enabled: true
camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
    lastName: Demo
  filter:
    create: All Tasks
  default-serialization-format: application/json
  generic-properties:
    properties:
      initializeTelemetry: false
  client:
    base-url: http://localhost:8080/engine-rest
    lock-duration: 20000
    async-response-timeout: 60000
server.port: 8080
sendgrid:
  api.key:
  user:
spring.profiles.active: 'dev'